name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - run: |
#         distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
#               && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
#               && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
#                     sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
#                     sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list && \
#                     sudo apt-get update && \
#                     sudo apt-get install -y nvidia-container-toolkit && \
#                     sudo apt-get install -y nvidia-container-csv-cuda && \
#                     sudo apt-get install -y nvidia-container-csv-cudnn && \
#                     sudo apt-get install -y nvidia-container-csv-tensorrt && \
#                     sudo nvidia-ctk runtime configure --runtime=docker && \
#                     sudo systemctl restart docker && \
#                     sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi
        
    - run: |
        sudo apt-get update && \
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && \
        sudo apt-get update && \
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && \
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list && \
        sudo apt-get update && \
        sudo apt-get install nvidia-docker2 && \
        sudo systemctl restart docker.service && \
        sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi

        
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
#     - uses: actions/checkout@v2
#     - run: source script-linux.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
